name: Build and deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/workflows/deploy.yml'
      - '.github/workflows/build_run.yml'
      - '.github/workflows/check_compose.yml'
      - 'docker-compose.yml'

defaults:
  run:
    shell: bash

jobs:
  build:
    concurrency:
      group: ${{ github.job }}-${{ github.ref_name }}
      cancel-in-progress: true
    name: Build
    runs-on: ubuntu-22.04
    outputs:
      image_name: ${{ steps.image-tag-name.outputs.image_name }}
      image_tag: ${{ steps.image-tag-name.outputs.tag }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get previous tag
        id: previous-tag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: 1.0.0

      - name: Check if it is new version
        id: check-version
        run: |
          CHANGED=( $(git diff ${{ steps.previous-tag.outputs.tag }}..HEAD --name-only) )
          echo "Changed files since last tag (${{ steps.previous-tag.outputs.tag }}):"
          printf '%s\n' "${CHANGED[@]}"
          
          while read LINE; do
            CHANGED=( $(printf '%s\n' "${CHANGED[@]}" | grep -v "^$LINE" | cat) )

            if [[ -z "${CHANGED[@]}" ]]; then
              echo "All files are in .dockerignore -> no new version"
              exit 0
            fi
          done < .dockerignore

          if [[ -n "${CHANGED[@]}" ]]; then
              echo new-version=true >> $GITHUB_OUTPUT
              echo "Files"
              printf '%s\n' "${CHANGED[@]}"
              echo "are not in .dockerignore -> it's new version"
          fi

      - name: Get commit message
        if: ${{ steps.check-version.outputs.new-version }}
        run: |
          COMMIT_MSG="$(git log --pretty=format:"%s" -n 1)"
          VERSION_FRAGMENT=$(echo $COMMIT_MSG | awk '{ print $1 }' | sed 's/://g')
          if [[ "$VERSION_FRAGMENT" != 'feature' && "$VERSION_FRAGMENT" != 'major' && "$VERSION_FRAGMENT" != 'bug' ]]; then
            VERSION_FRAGMENT='bug'
          fi
          echo "VERSION_FRAGMENT=$VERSION_FRAGMENT" >> $GITHUB_ENV

      - name: Bump patch version
        if: ${{ steps.check-version.outputs.new-version }}
        id: bump-version
        uses: christian-draeger/increment-semantic-version@1.0.2
        with:
          current-version: ${{ steps.previous-tag.outputs.tag }}
          version-fragment: ${{ env.VERSION_FRAGMENT }}

      - name: Make changelog
        if: ${{ steps.check-version.outputs.new-version }}
        id: changelog
        run: |
          MY_SHA="$(git log -1 --format=format:"%h" ${{ steps.previous-tag.outputs.tag }})"
          GIT_LOG="$(git log --pretty=format:"* %s" $MY_SHA..HEAD | uniq)"
          echo "### Changes" > RELEASE.md
          echo "$GIT_LOG" >> RELEASE.md

      - name: Create release
        if: ${{ steps.check-version.outputs.new-version }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.bump-version.outputs.next-version }}
          release_name: v${{ steps.bump-version.outputs.next-version }}
          draft: false
          prerelease: false
          body_path: RELEASE.md

      - run: |
          echo tag=${{ steps.bump-version.outputs.next-version || steps.previous-tag.outputs.tag }} >> $GITHUB_OUTPUT
          echo image_name=${{ vars.DOCKER_REGISTRY }}/${{ github.repository }} >> $GITHUB_OUTPUT
        id: image-tag-name

      - name: Set result tag
        id: set-tag
        run: |

          docker login ${{ vars.DOCKER_REGISTRY }} -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ github.token }}
          docker build . \
            -t ${{ steps.envs.outputs.image_name }}:$TAG \
            -t ${{ steps.envs.outputs.image_name }}:latest
          docker push ${{ steps.envs.outputs.image_name }}:$TAG
          docker push ${{ steps.envs.outputs.image_name }}:latest

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.envs.outputs.image_name }}:$TAG,${{ steps.envs.outputs.image_name }}:latest
          cache-from: type=registry,ref=${{ steps.envs.outputs.image_name }}:buildcache
          cache-to: type=registry,ref=${{ steps.envs.outputs.image_name }}:buildcache,mode=max

      - name: Failure notify
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ❌ ${{ github.actor }} pushed changes and job ${{ github.job }} failed.
            see workflow run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

  deploy:
    name: Deploy
    needs:
      - build
    uses: murtll/mcserver-backend/.github/workflows/deploy.yml@master
    if: ${{ github.ref_name == 'master' }}
    secrets: inherit
    with:
      image: ${{ needs.build.outputs.image_name }}
      tag: ${{ needs.build.outputs.image_tag }}
