name: Build and deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'
      - 'docker-compose.yml'
      - '.gitiignore'

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    outputs:
      image_name: ${{ steps.envs.outputs.image_name }}
      image_tag: ${{ steps.bump-version.outputs.next-version }}
    steps:
      - uses: actions/checkout@v2

      - run: |
          echo image_name=${GITHUB_REPOSITORY##*/} >> $GITHUB_OUTPUT
          echo image_tag=$(echo $GITHUB_SHA | cut -c 1-8) >> $GITHUB_OUTPUT
        id: envs

      - name: Get previous tag
        id: previous-tag
        uses: WyriHaximus/github-action-get-previous-tag@v1

      - name: Get commit message
        run: |
          COMMIT_MSG="$(git log --pretty=format:"%s" -n 1)"
          VERSION_FRAGMENT=$(echo $COMMIT_MSG | awk '{ print $1 }' | sed 's/://g')
          if [[ "$VERSION_FRAGMENT" != 'feature' && "$VERSION_FRAGMENT" != 'major' && "$VERSION_FRAGMENT" != 'bug' ]]; then
            VERSION_FRAGMENT='bug'
          fi
          echo "VERSION_FRAGMENT=$VERSION_FRAGMENT" >> $GITHUB_ENV

      - name: Bump patch version
        id: bump-version
        uses: christian-draeger/increment-semantic-version@1.0.2
        with:
          current-version: ${{ steps.previous-tag.outputs.tag }}
          version-fragment: ${{ env.VERSION_FRAGMENT }}

      - name: Make changelog
        continue-on-error: true
        id: changelog
        shell: bash
        run: |
          MY_SHA="$(git log -1 --format=format:"%h" ${{ steps.previous-tag.outputs.tag }})"
          GIT_LOG="$(git log --pretty=format:"%s" $MY_SHA..HEAD | uniq)"
          echo "$GIT_LOG" > RELEASE.md
          
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.bump-version.outputs.next-version }}
          release_name: v${{ steps.bump-version.outputs.next-version }}
          draft: false
          prerelease: false
          body_path: RELEASE.md

      - name: Build and push image
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          docker build . \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.envs.outputs.image_name }}:${{ steps.bump-version.outputs.next-version }} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.envs.outputs.image_name }}:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.envs.outputs.image_name }}:${{ steps.bump-version.outputs.next-version }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.envs.outputs.image_name }}:latest

      - name: Failure notify
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ❌ ${{ github.actor }} pushed changes and job ${{ github.job }} failed.
            see workflow run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

  deploy:
    name: Deploy
    needs:
      - build
    uses: murtll/mcserver-backend/.github/workflows/deploy.yml@master
    secrets: inherit
    with:
      image: ${{ needs.build.outputs.image_name }}
      tag: ${{ needs.build.outputs.image_tag }}