name: Build and run

on:
  pull_request:
    branches:
      - master

jobs:
  build_run:
    name: Build and run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build image
        run: |
          docker build -t ${{ github.repository }} .

      - name: Run container
        run: |
          mkdir -p data/
          touch data/database.db          
          docker run -d --name test -e PORT=${{ env.PORT }} -v $(pwd)/data/:/app/data ${{ github.repository }}
          sleep 5
          docker exec test wget --no-verbose --tries=1 --spider http://localhost:${{ env.PORT }}/
        env:
          PORT: 3000
